# Perform all actions as $POSTGRES_USER
export PGUSER=$POSTGRES_USER
POSTGRES_TEST_DB=$POSTGRES_TEST_DB
POSTGRES_IM_DB=$POSTGRES_IM_DB

echo "<<<< CREATING TEST & IM DATABASE >>>>"
echo
"${psql[@]}" --username $PGUSER <<-EOSQL
CREATE DATABASE "$POSTGRES_TEST_DB";
CREATE DATABASE "$POSTGRES_IM_DB";
EOSQL
echo
echo "<<<< COMPLETE >>>>"
